@startuml
package "administrator-management Bounded Context" {

    package "domain" {

            package "exceptions" {
            }
        package "Model" {
            package "aggregates" {
             class Administrator<<"aggregate">>{
             }
            }
            package "commands" {
            class CreateAdministratorCommand {
            }

            }
            package "queries" {
            }
            package "valueobjects" {
             class ProfileId<<record>>{
             }


            }
            package "entities" {
            }
            package "events"{
            }
        }

            package "services" {
            }

    }

    package "application" {
        package "Internal" {

        package "outboundeservices.acl"{

        }
            package "commandservices" {
            }
            package "queryservices" {
            }

            package "eventhandlers" {
            }

        }
    }

    package "infrastructure" {
        package "persistence.jpa.repositories" {
        }
    }
     package "interfaces.rest" {
                package "resources" {
                }
                package "transform" {
                }

            }
            package "interfaces.acl"{
            }


}
@enduml