@startuml
package "NursingHome Bounded Context" {

    package "Domain" {
        package "services"{
            interface "NursingHomeCommandService"{
                + handle(CreateNursingHomeCommand): Optional<NursingHome>
            }
            interface "NursingHomeQueryService"{
                + handle(GetAllNursingHomeQuery): List<NursingHome>
                + handle(GetNursingHomeByIdQuery): Optional<NursingHome>
            }
            interface "HeadQuarterCommandService"{
                + handle(CreateHeadQuarterCommand): Long
            }
            interface "HeadQuarterQueryService"{
                + handle(GetHeadQuarterByIdQuery): Optional<Headquarter>
                + handle(GetAllHeadQuarterByNursingHomeIdQuery): List<Headquarter>
            }
        }

        package "exceptions" {
            class AdministratorIdCannotBeNullException
            class DescriptionCannotBeNullException
            class DuplicateNameException
            class DuplicatePhoneNumberException
            class DuplicateRucException
            class InvalidDescriptionLengthException
            class InvalidRucLengthException
            class NameCannotBeNullException
            class NonPositiveAdministratorIdException
            class NullAddressException
            class PhoneNumberCannotBeNullException
            class RucCannotBeNullException
        }

        package "Model" {
            package "Aggregates" {
                class "NursingHome" {
                    - id: Long
                    - name: Name
                    - phoneNumber: PhoneNumber
                    - address: Address
                    - ruc: Ruc
                    - description: Description
                    + NursingHome()
                    + NursingHome(CreateNursingHomeCommand)
                }
            }

            package "Commands" {
                class CreateHeadQuarterCommand {
                    + nursingHomeId: Long
                    + title: String
                    + address: String
                }

                class CreateNursingHomeCommand {
                    + name: String
                    + ruc: String
                    + phoneNumber: String
                    + address: String
                    + description: String
                }

                class DeleteHeadQuarterCommand
                class UpdateHeadQuarterCommand
                class UpdateNursingHomeCommand
            }

            package "Queries" {
                class GetAllHeadQuarterByNursingHomeIdQuery {
                    + id: Long
                }

                class GetAllNursingHomeQuery

                class GetHeadQuarterByIdQuery {
                    + id: Long
                }

                class GetNursingHomeByIdQuery {
                    + id: Long
                }
            }

            package "Value Objects" {
                class Address<<record>> {
                    + address: String
                }

                class AdministratorId<<record>> {
                    + administratorId: Long
                }

                class Description<<record>> {
                    + description: String
                }

                class Name<<record>> {
                    + name: String
                }

                class PhoneNumber<<record>> {
                    + phoneNumber: String
                }

                class Ruc<<record>> {
                    + ruc: String
                }
            }

            package "entities" {
                class "Headquarter"{
                    - id: Long
                    - nursingHome: NursingHome
                    - title: String
                    - address: Address
                    + Headquarter()
                    + Headquarter(NursingHome, String, Address)
                    + updateTitle(String): void
                    + updateAddress(Address): void
                }
            }

            package "events"{
            }
        }
    }

    package "application" {
        package "Internal" {
            package "outboundeservices.acl"{
            }

            package "commandservices" {
                class HeadQuarterCommandServiceImpl {
                    - headQuarterRepository: HeadQuarterRepository
                    - nursingHomeRepository: NursingHomeRepository
                    + handle(CreateHeadQuarterCommand): Long
                }

                class NursingHomeCommandServiceImpl {
                    - nursingHomeRepository: NursingHomeRepository

                    + handle(CreateNursingHomeCommand): Optional<NursingHome>
                }
            }

            package "queryservices" {
                class HeadQuarterQueryServiceImpl {
                    - headQuarterRepository: HeadQuarterRepository
                    + handle(GetHeadQuarterByIdQuery): Optional<Headquarter>
                    + handle(GetAllHeadQuarterByNursingHomeIdQuery): List<Headquarter>
                }

                class NursingHomeQueryServiceImpl {
                    - nursingHomeRepository: NursingHomeRepository
                    + handle(GetAllNursingHomeQuery): List<NursingHome>
                    + handle(GetNursingHomeByIdQuery): Optional<NursingHome>
                }
            }
        }
    }

    package "infrastructure" {
        package "persistence.jpa.repositories" {
            interface HeadQuarterRepository {
                + findAllByNursingHomeId(Long): List<Headquarter>
            }

            interface NursingHomeRepository {
                + existsByName(Name): boolean
                + existsByRuc(Ruc): boolean
                + existsByPhoneNumber(PhoneNumber): boolean
            }
        }
    }

    package "interfaces.rest" {
        package "resources" {
            class CreateHeadQuarterResource<<record>> {
                + title: String
                + address: String
            }

            class CreateNursingHomeResource<<record>> {
                + name: String
                + ruc: String
                + phoneNumber: String
                + address: String
                + description: String
            }

            class HeadQuarterResource<<record>> {
                + id: Long
                + nursingHomeId: Long
                + title: String
                + address: String
            }

            class NursingHomeResource<<record>> {
                + id: Long
                + name: String
                + ruc: String
                + phoneNumber: String
                + address: String
                + description: String
            }

            class UpdateNursingHomeResource<<record>>
            class UpdateHeadQuarterResource<<record>>
        }

        package "transform" {
            class CreateHeadQuarterCommandFromResourceAssembler {
                + {static} toCommandFromResource(Long, CreateHeadQuarterResource): CreateHeadQuarterCommand
            }

            class CreateNursingHomeCommandFromResourceAssembler {
                + {static} toCommandFromResource(CreateNursingHomeResource): CreateNursingHomeCommand
            }

            class HeadQuarterResourceFromEntityAssembler {
                + {static} toResourceFromEntity(Headquarter): HeadQuarterResource
            }

            class NursingHomeResourceFromEntityAssembler {
                + {static} toCommandFromEntity(NursingHome): NursingHomeResource
            }

            class UpdateHeadQuarterCommandFromResourceAssembler
            class UpdateNursingHomeCommandFromResourceAssembler
        }

        class HeadQuartersController {
            - headQuarterCommandService: HeadQuarterCommandService
            - headQuarterQueryService: HeadQuarterQueryService
            + createdHeadQuarter(Long, CreateHeadQuarterResource): ResponseEntity<HeadQuarterResource>
            + GetAllHeadQuartersByNursingHomeId(Long): ResponseEntity<List<HeadQuarterResource>>
        }

        class NursingHomesController {
            - nursingHomeCommandService: NursingHomeCommandService
            - nursingHomeQueryService: NursingHomeQueryService
            + createNursingHome(CreateNursingHomeResource): ResponseEntity<NursingHomeResource>
            + getAllNursingHome(): ResponseEntity<List<NursingHomeResource>>
            + getNursingHomeById(Long): ResponseEntity<NursingHomeResource>
        }
    }

    package "interfaces.acl"{
    }
}

NursingHome *-- Name
NursingHome *-- Ruc
NursingHome *-- PhoneNumber
NursingHome *-- Address
NursingHome *-- Description
NursingHome ..> CreateNursingHomeCommand : uses

Headquarter *-- Address
Headquarter --> NursingHome : belongs to

NursingHomeCommandServiceImpl ..|> NursingHomeCommandService
NursingHomeCommandServiceImpl --> NursingHomeRepository
NursingHomeCommandServiceImpl ..> CreateNursingHomeCommand : handles
NursingHomeCommandServiceImpl ..> NursingHome : creates

HeadQuarterCommandServiceImpl ..|> HeadQuarterCommandService
HeadQuarterCommandServiceImpl --> HeadQuarterRepository
HeadQuarterCommandServiceImpl --> NursingHomeRepository
HeadQuarterCommandServiceImpl ..> CreateHeadQuarterCommand : handles
HeadQuarterCommandServiceImpl ..> Headquarter : creates

NursingHomeQueryServiceImpl ..|> NursingHomeQueryService
NursingHomeQueryServiceImpl --> NursingHomeRepository
NursingHomeQueryServiceImpl ..> GetAllNursingHomeQuery : handles
NursingHomeQueryServiceImpl ..> GetNursingHomeByIdQuery : handles

HeadQuarterQueryServiceImpl ..|> HeadQuarterQueryService
HeadQuarterQueryServiceImpl --> HeadQuarterRepository
HeadQuarterQueryServiceImpl ..> GetHeadQuarterByIdQuery : handles
HeadQuarterQueryServiceImpl ..> GetAllHeadQuarterByNursingHomeIdQuery : handles


NursingHomesController --> NursingHomeCommandService
NursingHomesController --> NursingHomeQueryService
NursingHomesController ..> CreateNursingHomeResource : receives
NursingHomesController ..> NursingHomeResource : returns

HeadQuartersController --> HeadQuarterCommandService
HeadQuartersController --> HeadQuarterQueryService
HeadQuartersController ..> CreateHeadQuarterResource : receives
HeadQuartersController ..> HeadQuarterResource : returns

CreateNursingHomeCommandFromResourceAssembler ..> CreateNursingHomeResource : transforms
CreateNursingHomeCommandFromResourceAssembler ..> CreateNursingHomeCommand : creates

CreateHeadQuarterCommandFromResourceAssembler ..> CreateHeadQuarterResource : transforms
CreateHeadQuarterCommandFromResourceAssembler ..> CreateHeadQuarterCommand : creates

NursingHomeResourceFromEntityAssembler ..> NursingHome : transforms
NursingHomeResourceFromEntityAssembler ..> NursingHomeResource : creates

HeadQuarterResourceFromEntityAssembler ..> Headquarter : transforms
HeadQuarterResourceFromEntityAssembler ..> HeadQuarterResource : creates

NursingHomesController ..> CreateNursingHomeCommandFromResourceAssembler : uses
NursingHomesController ..> NursingHomeResourceFromEntityAssembler : uses
HeadQuartersController ..> CreateHeadQuarterCommandFromResourceAssembler : uses
HeadQuartersController ..> HeadQuarterResourceFromEntityAssembler : uses

@enduml