@startuml
package "Profiles Bounded Context" {
     package "interfaces" {
        package "rest" {
          class ProfilesController {
            +createProfile(createProfileResource): ResponseEntity<ProfileResource>
            +getProfileById(profileId: Long): ResponseEntity<ProfileResource>
          }

          package "resources" {
            class ProfileResource {
              +id: Long
              +fullName: String
              +email: String
              +streetAddress: String
            }
            class CreateProfileResource {
              +firstName: String
              +lastName: String
              +email: String
              +street: String
              +number: String
              +city: String
              +postalCode: String
              +country: String
            }
          }

          package "transform" {
            class ProfileResourceFromEntityAssembler {
              +toResourceFromEntity(entity: Profile): ProfileResource {static}
            }
            class CreateProfileCommandFromResourceAssembler {
              +toCommandFromResource(resource: CreateProfileResource): CreateProfileCommand {static}
            }
          }
        }

        package "acl" {
          class ProfilesContextFacade {
            +createProfile(firstName: String, lastName: String, email: String, street: String, number: String, city: String, postalCode: String, country: String): Long
            +fetchProfileIdByEmail(email: String): Long
          }
          class ProfilesContextFacadeImpl {
            -profileCommandService: ProfileCommandService
            -profileQueryService: ProfileQueryService
            +createProfile(firstName: String, lastName: String, email: String, street: String, number: String, city: String, postalCode: String, country: String): Long
            +fetchProfileIdByEmail(email: String): Long
          }
        }
      }

      package "application" {
        package "internal" {
          package "commandservices" {
            class ProfileCommandServiceImpl {
              +handle(CreateProfileCommand): Optional<Profile>
            }
          }

          package "queryservices" {
            class ProfileQueryServiceImpl {
              +handle(GetProfileByIdQuery) : Optional<Profile>
              +handle(GetAllProfilesQuery) : List<Profile>
            }
          }
        }
      }

      package "domain" {
        package "model" {
          package "aggregates" {
            class Profile <<aggregate>> {
              -name: PersonName
              -emailAddress: EmailAddress
              -streetAddress: StreetAddress
              +getFullName(): String
              +getEmailAddress(): String
              +getStreetAddress(): String
              +updateName(firstName,lastName): void
              +updateEmailAddress(email): void
            }
          }

          package "commands" {
            class CreateProfileCommand
          }
          package "queries" {
            class GetProfileByIdQuery
          }
          package "valueobjects" {
            class PersonName
            class EmailAddress
            class StreetAddress
          }
        }
      }

      package "domain.services" {
        class ProfileCommandService {
          +handle(CreateProfileCommand): Optional<Profile>
        }
        class ProfileQueryService {
          +handle(GetProfileByIdQuery): Optional<Profile>
          +handle(GetProfileByEmailQuery): Optional<Profile>
          +handle(GetAllProfilesQuery): List<Profile>
        }


}
@enduml
