@startuml
package "resident-management Bounded Context" {

    package "domain" {

            package "exceptions" {
              class "ResidentAlreadyExistsException" <<exception>> {
                }
            }
        package "Model" {
            package "aggregates" {
            class "Resident"<<aggregate>>{
               -id: Long
               -profileId: profileId
                -roomId: roomId
                -emergencyContact: EmergencyContact
                -legalRepresentative: LegalRepresentative

            }
            }
            package "commands" {
            class "CreateResidentCommand"{
            }
            class "UpdateResidentCommand"{
                         nursingHomeId: NursingHomeId, Long residentId

            }
            class "DeleteResidentCommand"{
                         nursingHomeId: NursingHomeId, Long residentId

            }

            }
            package "queries" {
            class "GetAllResidentsByNursingHomeQuery"{
               NursingHomeId: NursingHomeId
            }
            class "GetResidentByNursingHomeQuery"{
             nursingHomeId: NursingHomeId, Long residentId
            }
            }
            package "valueobjects" {
             class "Name"<<record>>{

            }
                class "PhoneNumber"<<record>>{

                }
                    class "ProfileId"<<record>>{

                    }
                    class "RoomId"<<record>>{

                    }
                    class "RelationShip"<<Enum>>{
                     Son
                     Daughter
                     Granddaughter
                     grandson
                     Brother
                     Sister
                    }

            }
            package "entities" {
            class "LegalRepresentative"{
             -LegalGuardian legalGuardian
            -PhoneNumber guardianPhone
            }
             class "EmergencyContact"{
             -EmergencyContact name
              -PhoneNumber phoneNumber
              -RelationShip relationShip
                                        }
            }
            package "events"{
             class "ResidentCreatedEvent" {
             +residentId  ResidentId
                       +nursingHomeId NursingHomeId
             }
            }
        }

            package "services" {
             class "ResidentCommandService"{
             +handle(CreateResidentCommand command),
                +handle(UpdateResidentCommand command),
                +handle(DeleteResidentCommand command)
             }

                class "ResidentQueryService"{
                +handle(GetAllResidentsByNursingHomeQuery query),
                +handle(GetResidentByNursingHomeQuery query)
                }
            }

    }

    package "application" {
        package "Internal" {

        package "outboundeservices.acl"{

        }
            package "commandservices" {
            class "ResidentCommandServiceImpl"{

            }

            }
            package "queryservices" {
            class "ResidentQueryServiceImpl"{
              handle (GetAllResidentsByNursingHomeQuery query):List<Resident>
              handle (GetResidentByNursingHomeQuery query):Optional<Resident>
            }
            }

            package "eventhandlers" {
            }

        }
    }

    package "infrastructure" {
        package "persistence.jpa.repositories" {
        class "ResidentRepository"{
         findAllByNursingHomeId(nursingHomeId: NursingHomeId): List<Resident>
         findByNursingHomeIdAndResidentId(nursingHomeId: NursingHomeId, residentId: Long): Optional<Resident>
        }
        }
    }
     package "interfaces.rest" {
                package "resources" {
                class "ResidentResource"{
                }
                class "CreateResidentResource"{
                }
                class "UpdateResidentResource"{
                }
                }
                package "transform" {
                class "CreateResidentCommandFromResourceAssembler"{
                }
                class "ResidentResourceFromEntityAssembler"{
                }
                }
             class "ResidentsController"{
             }
            }
            package "interfaces.acl"{
            }


}
@enduml